apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-green
  template:
    metadata:
      labels:
        app: messaging-green
    spec:
      containers:
        - name: messaging-app
          image: yourdockerhubusername/messaging-app:1.1
          ports:
         
